name: flutter_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  zoomable_image: 1.1.2
  path_provider: ^0.4.0
  sqflite: ^0.8.7
  shared_preferences: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - img/loading.png
